/**
 * @file qret/frontend/circuit_generator.h
 * @brief Generator of quantum circuits.
 * @details This file implements CircuitGenerator, which facilitates the description
 * of quantum circuits.
 *
 * CircuitGenerator is a class to be used through inheritance. It not only
 * describes circuits but also has the functionality to cache circuits within
 * CircuitBuilder.
 */

#ifndef QRET_FRONTEND_CIRCUIT_GENERATOR_H
#define QRET_FRONTEND_CIRCUIT_GENERATOR_H

#include <string_view>

#include "qret/frontend/argument.h"
#include "qret/frontend/circuit.h"
#include "qret/qret_export.h"

namespace qret::frontend {
// Forward declarations
class CircuitBuilder;

/**
 * @brief Generator of qret::frontend::Circuit.
 */
class QRET_EXPORT CircuitGenerator {
public:
    using Type = Circuit::Type;
    using Attribute = Circuit::Attribute;
    using Argument = Circuit::Argument;

    explicit CircuitGenerator(CircuitBuilder* builder)
        : builder_{builder} {}

    CircuitBuilder* GetBuilder() const {
        return builder_;
    }

    // Pure virtual methods

    /**
     * @brief Create a circuit.
     * @details Implement the circuit logic within the overridden method of this pure virtual
     * method.
     *
     * @return Circuit* a pointer to the created circuit
     */
    virtual Circuit* Generate() const = 0;
    /**
     * @brief Set the argument of the circuit to generate
     *
     * @param arg the argument of the circuit
     */
    virtual void SetArgument(Argument& arg) const = 0;
    /**
     * @brief Get the name of circuit to generate (not necessarily unique).
     *
     * @return std::string the name of circuit
     */
    virtual std::string GetName() const = 0;

    // Overridable hooks

    /**
     * @brief Create an adjoint circuit.
     * @details You can automatically create an adjoint circuit using the "Adjoint" function defined
     * in functor.h. If you want to define the adjoint circuit yourself instead of automatic
     * generation, override this method.
     *
     * If you override this method and create your own adjoint circuit, the "Adjoint" function
     * returns the one generated by this method.
     *
     * @return Circuit* adjoint circuit
     */
    virtual Circuit* GenerateAdjoint() const {
        return nullptr;
    }
    /**
     * @brief Get the cache key of the circuit to generate, which has a unique name.
     * @details Override this method only if the circuit begin created can be assigned a unique
     * name.
     *
     * @return std::string the cache key of a circuit with a unique name
     */
    virtual std::string GetCacheKey() const {
        return "";
    }

    /**
     * @brief If the circuit to generate is cached within the builder.
     *
     * @return true cached
     * @return false not cached
     */
    bool IsCached() const;
    /**
     * @brief Get the circuit cached within the builder.
     *
     * @return Circuit* cached circuit
     */
    Circuit* GetCachedCircuit() const;

    // template <typename T>
    // T Get(std::size_t arg_idx) const {}
    Qubit GetQubit(std::size_t arg_idx) const;
    Qubit GetQubit(std::string_view arg_name) const {
        return GetQubit(GetCircuit()->GetArgument().GetArgIdx(arg_name));
    }
    Qubits GetQubits(std::size_t arg_idx) const;
    Qubits GetQubits(std::string_view arg_name) const {
        return GetQubits(GetCircuit()->GetArgument().GetArgIdx(arg_name));
    }
    Register GetRegister(std::size_t arg_idx) const;
    Register GetRegister(std::string_view arg_name) const {
        return GetRegister(GetCircuit()->GetArgument().GetArgIdx(arg_name));
    }
    Registers GetRegisters(std::size_t arg_idx) const;
    Registers GetRegisters(std::string_view arg_name) const {
        return GetRegisters(GetCircuit()->GetArgument().GetArgIdx(arg_name));
    }

    Register GetTemporalRegister() const;
    Registers GetTemporalRegisters(std::size_t size) const;

protected:
    void BeginCircuitDefinition() const;
    Circuit* EndCircuitDefinition() const;

private:
    Circuit* GetCircuit() const {
        return circuit_;
    }

    CircuitBuilder* const builder_;
    mutable Circuit* circuit_ = nullptr;
    mutable std::uint64_t temporal_register_id_ = 0;
};
}  // namespace qret::frontend

#endif  // QRET_FRONTEND_CIRCUIT_GENERATOR_H
