/**
 * @file tests/frontend/qualtran.cpp
 * @brief Unit tests for the Qualtran → Quration IR frontend. Fixtures are generated by
 * gen_qualtran_test_data.py into quration-core/tests/data/qualtran/.
 */

#include "qret/frontend/qualtran.h"

#include <gtest/gtest.h>

#include <algorithm>
#include <cstdint>
#include <fstream>
#include <iterator>
#include <numbers>
#include <string>
#include <string_view>
#include <vector>

#include "qret/base/cast.h"
#include "qret/exception.h"
#include "qret/frontend/builder.h"
#include "qret/ir/basic_block.h"
#include "qret/ir/context.h"
#include "qret/ir/function.h"
#include "qret/ir/instruction.h"
#include "qret/ir/instructions.h"
#include "qret/ir/module.h"
#include "qret/ir/value.h"

using namespace qret;

namespace {

std::string ReadFile(const std::string& path) {
    auto ifs = std::ifstream(path);
    EXPECT_TRUE(ifs.good()) << "cannot open test data file: " << path;
    return {(std::istreambuf_iterator<char>(ifs)), std::istreambuf_iterator<char>()};
}

constexpr double kTol = 1e-12;

// Checks opcode and qubit operand ids; qubit_ids' size must match the instruction's arity.
void ExpectInstruction(
        const ir::Instruction* inst,
        ir::Opcode::Table opcode,
        const std::vector<std::uint64_t>& qubit_ids
) {
    EXPECT_EQ(opcode, inst->GetOpcode().GetCode());
    if (inst->IsUnary()) {
        ASSERT_EQ(1u, qubit_ids.size());
        EXPECT_EQ(qubit_ids[0], Cast<ir::UnaryInst>(inst)->GetQubit().id);
    } else if (inst->IsBinary()) {
        ASSERT_EQ(2u, qubit_ids.size());
        const auto* binary_inst = Cast<ir::BinaryInst>(inst);
        EXPECT_EQ(qubit_ids[0], binary_inst->GetQubit0().id);
        EXPECT_EQ(qubit_ids[1], binary_inst->GetQubit1().id);
    } else if (inst->IsTernary()) {
        ASSERT_EQ(3u, qubit_ids.size());
        const auto* ternary_inst = Cast<ir::TernaryInst>(inst);
        EXPECT_EQ(qubit_ids[0], ternary_inst->GetQubit0().id);
        EXPECT_EQ(qubit_ids[1], ternary_inst->GetQubit1().id);
        EXPECT_EQ(qubit_ids[2], ternary_inst->GetQubit2().id);
    } else {
        FAIL() << "instruction is neither Unary, Binary, nor Ternary";
    }
}

void ExpectGlobalPhase(const ir::Instruction* inst, double value, double precision) {
    ASSERT_EQ(ir::Opcode::Table::GlobalPhase, inst->GetOpcode().GetCode());
    const auto* gp = Cast<ir::GlobalPhaseInst>(inst);
    EXPECT_NEAR(value, gp->GetTheta().value, kTol);
    EXPECT_NEAR(precision, gp->GetTheta().precision, kTol);
}

void ExpectRotation(
        const ir::Instruction* inst,
        ir::Opcode::Table opcode,
        std::uint64_t qubit_id,
        double value,
        double precision
) {
    ASSERT_TRUE(inst->IsParametrizedRotation());
    const auto* ri = Cast<ir::ParametrizedRotationInst>(inst);
    EXPECT_EQ(opcode, ri->GetOpcode().GetCode());
    EXPECT_EQ(qubit_id, ri->GetQubit().id);
    EXPECT_NEAR(value, ri->GetTheta().value, kTol);
    EXPECT_NEAR(precision, ri->GetTheta().precision, kTol);
}

// Checks a CallInst's operand qubit ids, in order; returns the callee for further inspection.
const ir::Function*
ExpectCallOperands(const ir::Instruction* inst, const std::vector<std::uint64_t>& qubit_ids) {
    EXPECT_EQ(ir::Opcode::Table::Call, inst->GetOpcode().GetCode());
    const auto* call = Cast<ir::CallInst>(inst);
    EXPECT_NE(call->GetCallee(), nullptr);
    EXPECT_EQ(qubit_ids.size(), call->GetOperate().size());
    for (auto i = std::size_t{0}; i < qubit_ids.size() && i < call->GetOperate().size(); ++i) {
        EXPECT_EQ(qubit_ids[i], call->GetOperate()[i].id);
    }
    return call->GetCallee();
}

// Returns the instruction at itr and advances it; fails if itr is already at bb's end.
const ir::Instruction* Next(ir::BasicBlock::const_iterator& itr, const ir::BasicBlock* bb) {
    if (itr == bb->end()) {
        ADD_FAILURE() << "iterator reached end of basic block prematurely";
        return nullptr;
    }
    const ir::Instruction* inst = itr.GetPointer();
    ++itr;
    return inst;
}

// Builds a Circuit from quration-core/tests/data/qualtran/<name>.json.
class QualtranFixture {
public:
    explicit QualtranFixture(std::string_view name)
        : name_(name)
        , module_(ir::Module::Create(name, context_))
        , builder_(module_) {}

    frontend::Circuit* Build() {
        return BuildFromJson(ReadFile("quration-core/tests/data/qualtran/" + name_ + ".json"));
    }
    frontend::Circuit* BuildFromJson(const std::string& json) {
        return frontend::BuildCircuitFromQualtranJson(json, builder_, "main");
    }

private:
    std::string name_;
    ir::IRContext context_;
    ir::Module* module_;
    frontend::CircuitBuilder builder_;
};

}  // namespace

// Every directly-mapped gate, including TDag/SDag (is_adjoint=True, not Adjoint(subbloq)).
TEST(QualtranFrontend, DirectGates) {
    QualtranFixture fx("direct_gates");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(7u, func->GetNumQubits());
    EXPECT_EQ(14u, func->GetInstructionCount());  // 13 gates + Return

    struct Expected {
        ir::Opcode::Table opcode;
        std::vector<std::uint64_t> qubit_ids;
    };
    const Expected expected[] = {
            {ir::Opcode::Table::X, {0}},
            {ir::Opcode::Table::Y, {2}},
            {ir::Opcode::Table::Z, {3}},
            {ir::Opcode::Table::CX, {1, 0}},
            {ir::Opcode::Table::H, {1}},
            {ir::Opcode::Table::CZ, {2, 1}},
            {ir::Opcode::Table::CY, {3, 2}},
            {ir::Opcode::Table::S, {3}},
            {ir::Opcode::Table::T, {3}},
            {ir::Opcode::Table::SDag, {3}},
            {ir::Opcode::Table::TDag, {3}},
            {ir::Opcode::Table::I, {3}},
            {ir::Opcode::Table::CCX, {6, 4, 5}},
    };

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();
    for (const auto& e : expected) {
        ASSERT_NE(itr, bb->end());
        ExpectInstruction(Next(itr, bb), e.opcode, e.qubit_ids);
    }
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// Rx/Ry/Rz, XPowGate/YPowGate/ZPowGate, CRz, SU2RotationGate. CZPowGate is covered separately by
// CzpowMultiple since it hides an And compute/uncompute pair.
TEST(QualtranFrontend, ParametrizedGates) {
    QualtranFixture fx("parametrized_gates");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(9u, func->GetNumQubits());

    constexpr double kAngle = std::numbers::pi / 4.0;
    constexpr double kEps = 1e-8;

    // SU2RotationGate(theta=0.1, phi=0.2, lambd=0.3, global_shift=0.4, eps=1e-8): mirrors
    // EmitSU2RotationGate's GlobalPhase(0.5 + alpha/pi + lambd/(2pi) + phi/(2pi)),
    // RZ(pi/2 - lambd), RX(2*theta), RZ(pi/2 - phi).
    constexpr double kSu2Theta = 0.1;
    constexpr double kSu2Phi = 0.2;
    constexpr double kSu2Lambd = 0.3;
    constexpr double kSu2Alpha = 0.4;
    const double kSu2GlobalPhase = 0.5 + kSu2Alpha / std::numbers::pi
            + kSu2Lambd / (2.0 * std::numbers::pi) + kSu2Phi / (2.0 * std::numbers::pi);
    const double kSu2Rz1 = std::numbers::pi / 2.0 - kSu2Lambd;
    const double kSu2Rx = 2.0 * kSu2Theta;
    const double kSu2Rz2 = std::numbers::pi / 2.0 - kSu2Phi;

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RX, 0u, kAngle, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RY, 1u, kAngle, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 2u, kAngle, kEps);

    // XPowGate(exponent=0.5): GlobalPhase(0.25) + RX(pi/2).
    ExpectGlobalPhase(Next(itr, bb), 0.25, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RX, 3u, std::numbers::pi * 0.5, kEps);
    // YPowGate(exponent=0.5): GlobalPhase(0.25) + RY(pi/2).
    ExpectGlobalPhase(Next(itr, bb), 0.25, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RY, 4u, std::numbers::pi * 0.5, kEps);
    // ZPowGate(exponent=0.5): GlobalPhase(0.25) + RZ(pi/2).
    ExpectGlobalPhase(Next(itr, bb), 0.25, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 5u, std::numbers::pi * 0.5, kEps);

    // CRz(angle=0.3, eps=1e-8): RZ(-0.15)-CX-RZ(0.15)-CX.
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 7u, 0.15, kEps / 2.0);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {7, 6});
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 7u, -0.15, kEps / 2.0);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {7, 6});

    ExpectGlobalPhase(Next(itr, bb), kSu2GlobalPhase, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 8u, kSu2Rz1, kEps / 3.0);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RX, 8u, kSu2Rx, kEps / 3.0);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 8u, kSu2Rz2, kEps / 3.0);

    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// CHadamard/TwoBitSwap/TwoBitCSwap, each a preset CallInst (not inlined).
TEST(QualtranFrontend, PresetGateCalls) {
    QualtranFixture fx("preset_gate_calls");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(7u, func->GetNumQubits());
    EXPECT_EQ(4u, func->GetInstructionCount());  // 3 calls + Return

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    {
        const ir::Function* ch_func = ExpectCallOperands(Next(itr, bb), {0, 1});
        EXPECT_EQ(2u, ch_func->GetNumQubits());
        EXPECT_EQ(8u, ch_func->GetInstructionCount());
    }
    {
        const ir::Function* sw_func = ExpectCallOperands(Next(itr, bb), {2, 3});
        EXPECT_EQ(2u, sw_func->GetNumQubits());
        EXPECT_EQ(4u, sw_func->GetInstructionCount());
    }
    {
        const ir::Function* csw_func = ExpectCallOperands(Next(itr, bb), {4, 5, 6});
        EXPECT_EQ(3u, csw_func->GetNumQubits());
        EXPECT_EQ(4u, csw_func->GetInstructionCount());
    }
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// And(compute)->And(uncompute) round trip, plus a separate And(cv1=0, cv2=1) compute-only leaf.
TEST(QualtranFrontend, AndGates) {
    QualtranFixture fx("and_gates");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(6u, func->GetNumQubits());
    EXPECT_EQ(6u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 5})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 5})->GetName())
    );
    EXPECT_EQ(
            "And_cv01__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {2, 3, 4})->GetName())
    );
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// Two atomic CZPowGate leaves (differing exponent), each drawing a non-overlapping slice of the
// shared anc_clean pool.
TEST(QualtranFrontend, CzpowMultiple) {
    QualtranFixture fx("czpow_multiple");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(6u, func->GetNumQubits());  // q1[2] + q2[2] + anc_clean[2].
    EXPECT_EQ(13u, func->GetInstructionCount());

    constexpr double kEps = 1e-8;

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());

    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 4})->GetName())
    );
    ExpectGlobalPhase(Next(itr, bb), 0.25, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 4u, std::numbers::pi * 0.5, kEps);
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 4})->GetName())
    );

    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {2, 3, 5})->GetName())
    );
    ExpectGlobalPhase(Next(itr, bb), 0.125, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 5u, std::numbers::pi * 0.25, kEps);
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {2, 3, 5})->GetName())
    );

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// Swap(bitsize=3)->CSwap(bitsize=3): decomposed and leaf serializations must produce the same IR.
void CheckSwapCswap(const ir::Function* func) {
    ASSERT_NE(func, nullptr);
    EXPECT_EQ(7u, func->GetNumQubits());
    EXPECT_EQ(3u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    {
        const ir::Function* swap_func = ExpectCallOperands(Next(itr, bb), {1, 2, 3, 4, 5, 6});
        EXPECT_EQ(6u, swap_func->GetNumQubits());
        EXPECT_EQ(4u, swap_func->GetInstructionCount());  // 3 x TwoBitSwap + Return
    }
    {
        const ir::Function* cswap_func = ExpectCallOperands(Next(itr, bb), {0, 1, 2, 3, 4, 5, 6});
        EXPECT_EQ(7u, cswap_func->GetNumQubits());
        EXPECT_EQ(4u, cswap_func->GetInstructionCount());  // 3 x TwoBitCSwap + Return
    }
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

TEST(QualtranFrontend, SwapCswapDecomposed) {
    QualtranFixture fx("swap_cswap_decomposed");
    auto* circuit = fx.Build();
    ASSERT_NE(circuit, nullptr);
    CheckSwapCswap(circuit->GetIR());
}

TEST(QualtranFrontend, SwapCswapLeaf) {
    QualtranFixture fx("swap_cswap_leaf");
    auto* circuit = fx.Build();
    ASSERT_NE(circuit, nullptr);
    CheckSwapCswap(circuit->GetIR());
}

// ZeroState/OneState/PlusState/MinusState, each immediately consumed by its own allocated qubit.
TEST(QualtranFrontend, StateBasis) {
    QualtranFixture fx("state_basis");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(4u, func->GetNumQubits());
    EXPECT_EQ(9u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // ZeroState(0): Clean only.
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // OneState(1): Clean + X.
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {1});
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // PlusState(2): Clean + H.
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::H, {2});
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // MinusState(3): Clean + X + H.
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {3});
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::H, {3});
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// Allocate/Free (clean and dirty), an unfreed Allocate escaping at the root boundary, and
// AllocatingSubBloq() escaping at a sub-circuit boundary (a different call site).
TEST(QualtranFrontend, ProducerBoundary) {
    QualtranFixture fx("producer_boundary");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(7u, func->GetNumQubits());  // x_thru + anc_escape[2] + sub_escape[2] + anc_clean +
                                           // anc_dirty.
    EXPECT_EQ(12u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean)
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // DirtyBegin(anc_dirty)
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean), Allocate's own hint
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {5});
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean), end of scope
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {6});
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_escape[0])
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_escape[1])

    // AllocatingSubBloq(): unfreed Allocate escapes at its own sub-circuit boundary.
    {
        const ir::Function* sub_func = ExpectCallOperands(Next(itr, bb), {3, 4});
        EXPECT_EQ(2u, sub_func->GetNumQubits());
        EXPECT_EQ(3u, sub_func->GetInstructionCount());  // Clean + Clean + Return
        const ir::BasicBlock* sub_bb = sub_func->GetEntryBB();
        auto si = sub_bb->begin();
        EXPECT_TRUE(Next(si, sub_bb)->IsOptHint());
        EXPECT_TRUE(Next(si, sub_bb)->IsOptHint());
        EXPECT_EQ(ir::Opcode::Table::Return, Next(si, sub_bb)->GetOpcode().GetCode());
    }

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean) again
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // DirtyEnd(anc_dirty)
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// IntState(val=5, bitsize=3) -> IntEffect(val=5, bitsize=3); both are non-atomic in Qualtran.
TEST(QualtranFrontend, IntStateEffect) {
    QualtranFixture fx("int_state_effect");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(3u, func->GetNumQubits());
    EXPECT_EQ(3u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    // IntState(val=5=0b101, MSB first): X on val[0] and val[2] only.
    {
        const ir::Function* sub_func = ExpectCallOperands(Next(itr, bb), {0, 1, 2});
        EXPECT_EQ(3u, sub_func->GetNumQubits());
        EXPECT_EQ(6u, sub_func->GetInstructionCount());
    }
    // IntEffect(val=5): Split emits no gate; only ZeroEffect asserts MarkAsClean.
    {
        const ir::Function* sub_func = ExpectCallOperands(Next(itr, bb), {0, 1, 2});
        EXPECT_EQ(3u, sub_func->GetNumQubits());
        EXPECT_EQ(2u, sub_func->GetInstructionCount());
    }
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// Allocate(1)->ZeroEffect (MarkAsClean fires, lands in anc_clean) alongside Allocate+X/H, actually
// preparing the claimed state, ->One/Plus/MinusEffect (no consumer-side MarkAsClean, lands in
// anc_operate). Qualtran's own Allocate/Free contract requires the freed qubit to genuinely be in
// the state the Effect claims, so One/Plus/MinusEffect consuming a bare |0> (never transformed
// away from Allocate's own guarantee) would not be a circuit Qualtran itself could produce.
TEST(QualtranFrontend, ConsumerVariants) {
    QualtranFixture fx("consumer_variants");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(4u, func->GetNumQubits());
    EXPECT_EQ(12u, func->GetInstructionCount());

    const auto& argument = circuit->GetArgument();
    ASSERT_EQ(2u, argument.GetNumArgs());
    EXPECT_EQ("anc_clean", argument.GetArgName(0));
    EXPECT_EQ(1u, argument.GetSize(0));  // Only ZeroEffect's qubit is CleanAncilla.
    EXPECT_EQ("anc_operate", argument.GetArgName(1));
    EXPECT_EQ(3u, argument.GetSize(1));  // One/Plus/MinusEffect's qubits are plain Operate.

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean), begin of scope.

    // Allocate marks its own qubit clean regardless of pool; ZeroEffect adds its own verification
    // mark on top (no gate in between, since |0> is already the state it claims).
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());

    // One/Plus/MinusEffect trust their basis-state contract without verification, so only
    // Allocate's own mark precedes the gate(s) that actually prepare the claimed state.
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {1});
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::H, {2});
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {3});
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::H, {3});

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean), end of scope.
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// Split2->Join2 (with an X sandwiched on one split bit), Cast, and Partition round trip -- none
// of these AliasOnly bloqs emit a gate of their own.
TEST(QualtranFrontend, AliasVariants) {
    QualtranFixture fx("alias_variants");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(13u, func->GetNumQubits());
    EXPECT_EQ(4u, func->GetInstructionCount());  // 3 X gates + Return

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {0});  // tag
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {1});  // one bit inside xs's Split2
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {5});  // p
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// Two OuterNamedGate instances (named custom Bloq, must resolve to the same shared Circuit), an
// anonymous 3-level CompositeBloq nesting, and two MyGateWithCZPow instances (each forwarding its
// own scratch ancilla to the root's anc_clean pool without colliding).
TEST(QualtranFrontend, SubcircuitVariants) {
    QualtranFixture fx("subcircuit_variants");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(12u, func->GetNumQubits());
    EXPECT_EQ(10u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());

    // Two OuterNamedGate instances: same underlying bloq, must resolve to the same Function.
    const ir::Function* outer_a = ExpectCallOperands(Next(itr, bb), {0, 1});
    const ir::Function* outer_b = ExpectCallOperands(Next(itr, bb), {2, 3});
    EXPECT_EQ(outer_a, outer_b);
    ASSERT_NE(outer_a, nullptr);
    EXPECT_NE(std::string::npos, std::string(outer_a->GetName()).find("OuterNamedGate"));
    EXPECT_EQ(2u, outer_a->GetNumQubits());
    EXPECT_EQ(3u, outer_a->GetInstructionCount());  // X + Call(InnerNamedGate) + Return

    // Anonymous 3-level nesting (outer->middle->inner).
    {
        const ir::Function* mid_func = ExpectCallOperands(Next(itr, bb), {4, 5});
        EXPECT_EQ(2u, mid_func->GetNumQubits());
        EXPECT_EQ(3u, mid_func->GetInstructionCount());  // H + Call(inner) + Return
    }

    // Two MyGateWithCZPow instances: distinct Functions despite the same underlying bloq name,
    // each forwarding its own CZPowGate scratch ancilla to the root's anc_clean pool.
    const ir::Function* sub_a = ExpectCallOperands(Next(itr, bb), {6, 7, 10});
    const ir::Function* sub_b = ExpectCallOperands(Next(itr, bb), {8, 9, 11});
    ASSERT_NE(sub_a, nullptr);
    ASSERT_NE(sub_b, nullptr);
    EXPECT_NE(sub_a, sub_b);
    for (const ir::Function* sub_func : {sub_a, sub_b}) {
        EXPECT_EQ(3u, sub_func->GetNumQubits());
        EXPECT_EQ(4u, sub_func->GetInstructionCount());  // Clean + Call(CZPowGate) + Clean + Return
    }

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// Every AdjointWrapper scenario: custom composite reversal, self-adjoint preset, inlined Gate
// terminal, name resolution across differently-parameterized instances, even/odd nesting depth,
// AliasOnly, a composite with its own CleanAncilla, and Producer/Consumer role flip.
TEST(QualtranFrontend, AdjointVariants) {
    QualtranFixture fx("adjoint_variants");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(22u, func->GetNumQubits());
    EXPECT_EQ(27u, func->GetInstructionCount());

    constexpr double kEps = 1e-8;

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    // anc_clean holds all three And-pair/CleanAncilla scratch qubits below; there is no
    // anc_operate pool (nothing here needs it).
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean[0])
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean[1])
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean[2])

    // Adjoint(MyGate()): reversed order (H, X).
    {
        const ir::Function* adj_func = ExpectCallOperands(Next(itr, bb), {0});
        EXPECT_EQ(1u, adj_func->GetNumQubits());
        EXPECT_EQ(3u, adj_func->GetInstructionCount());
        const ir::BasicBlock* adj_bb = adj_func->GetEntryBB();
        auto adj_itr = adj_bb->begin();
        ExpectInstruction(Next(adj_itr, adj_bb), ir::Opcode::Table::H, {0});
        ExpectInstruction(Next(adj_itr, adj_bb), ir::Opcode::Table::X, {0});
        EXPECT_EQ(ir::Opcode::Table::Return, Next(adj_itr, adj_bb)->GetOpcode().GetCode());
    }

    // Adjoint(CHadamard()): self-adjoint, unreversed order.
    {
        const ir::Function* ch_func = ExpectCallOperands(Next(itr, bb), {1, 2});
        EXPECT_EQ(2u, ch_func->GetNumQubits());
        EXPECT_EQ(8u, ch_func->GetInstructionCount());
    }

    // Adjoint(CRz(angle=0.3, eps=1e-8)): inlined, angle negated: RZ(-0.15)-CX-RZ(0.15)-CX.
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 4u, -0.15, kEps / 2.0);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {4, 3});
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 4u, 0.15, kEps / 2.0);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {4, 3});

    // Adjoint(MyRzGate(angle=0.3)) and Adjoint(MyRzGate(angle=0.7)): distinct Circuits, each
    // with its own angle negated -- neither collides nor swaps its angle with the other.
    {
        const ir::Function* rz_a = ExpectCallOperands(Next(itr, bb), {5});
        EXPECT_NE(std::string::npos, std::string(rz_a->GetName()).find("MyRzGate"));
        EXPECT_EQ(2u, rz_a->GetInstructionCount());  // RZ + Return
        ExpectRotation(rz_a->GetEntryBB()->begin().GetPointer(), ir::Opcode::Table::RZ, 0u, -0.3, kEps);

        const ir::Function* rz_b = ExpectCallOperands(Next(itr, bb), {6});
        EXPECT_NE(std::string::npos, std::string(rz_b->GetName()).find("MyRzGate"));
        EXPECT_EQ(2u, rz_b->GetInstructionCount());
        ExpectRotation(rz_b->GetEntryBB()->begin().GetPointer(), ir::Opcode::Table::RZ, 0u, -0.7, kEps);

        EXPECT_NE(rz_a, rz_b);
    }

    // Adjoint(SU2RotationGate(theta, phi, lambd, global_shift)): same params as parametrized_gates'
    // non-adjoint case, for direct comparison. Mirrors EmitSU2RotationGate's own formula with
    // phi/lambd swapped and negated, global_shift negated, and theta untouched (matches
    // EmitGate's is_adjoint dispatch for SU2RotationGate).
    constexpr auto kSu2Theta = 0.1;
    constexpr auto kSu2Phi = 0.2;
    constexpr auto kSu2Lambd = 0.3;
    constexpr auto kSu2GlobalShift = 0.4;
    constexpr auto kSu2AdjPhi = -kSu2Lambd;
    constexpr auto kSu2AdjLambd = -kSu2Phi;
    constexpr auto kSu2AdjGlobalShift = -kSu2GlobalShift;
    ExpectGlobalPhase(
            Next(itr, bb),
            0.5 + kSu2AdjGlobalShift / std::numbers::pi
                    + kSu2AdjLambd / (2.0 * std::numbers::pi)
                    + kSu2AdjPhi / (2.0 * std::numbers::pi),
            kEps
    );
    ExpectRotation(
            Next(itr, bb),
            ir::Opcode::Table::RZ,
            7u,
            std::numbers::pi / 2.0 - kSu2AdjLambd,
            kEps / 3.0
    );
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RX, 7u, 2.0 * kSu2Theta, kEps / 3.0);
    ExpectRotation(
            Next(itr, bb),
            ir::Opcode::Table::RZ,
            7u,
            std::numbers::pi / 2.0 - kSu2AdjPhi,
            kEps / 3.0
    );

    // Adjoint(Rz(angle=pi/4)): inlined via the shared `sign` dispatch, angle negated.
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 8u, -std::numbers::pi / 4.0, kEps);

    // Even (2-layer) Adjoint(Adjoint(And())) resolves back to compute direction.
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {9, 10, 19})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {9, 10, 19})->GetName())
    );

    // Odd (3-layer) Adjoint(Adjoint(Adjoint(And()))) flips to uncompute direction: same
    // producer/consumer shape as the even case above, so its ancilla is Clean too (anc_clean[1]).
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {11, 12, 20})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {11, 12, 20})->GetName())
    );

    // Adjoint(Split(...)) is AliasOnly: no gate for x_split (qubits 13, 14 never appear).

    // Adjoint(AndWithGatesGate()): custom composite with its own CleanAncilla (anc_clean[2]).
    {
        const ir::Function* adj_func = ExpectCallOperands(Next(itr, bb), {15, 16, 21});
        EXPECT_EQ(3u, adj_func->GetNumQubits());
        EXPECT_EQ(6u, adj_func->GetInstructionCount());
    }

    // Adjoint(ZeroState())/Adjoint(ZeroEffect()): both flip to MarkAsClean (odd depth).
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(q_state)
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(q_effect)

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean[0]), end of scope
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean[1]), end of scope
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // Clean(anc_clean[2]), end of scope
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// Adjoint(MyGate()) serialized at max_depth=2, so Qualtran expands the Adjoint wrapper itself
// into a Composite rather than leaving it an AdjointWrapper atom.
TEST(QualtranFrontend, AdjointDecomposed) {
    QualtranFixture fx("adjoint_decomposed");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(1u, func->GetNumQubits());
    EXPECT_EQ(2u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    const ir::Function* sub_func = ExpectCallOperands(Next(itr, bb), {0});
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());

    ASSERT_NE(sub_func, nullptr);
    EXPECT_EQ(1u, sub_func->GetNumQubits());
    EXPECT_EQ(3u, sub_func->GetInstructionCount());  // H, X, Return -- MyGate's adjoint order.

    const ir::BasicBlock* sub_bb = sub_func->GetEntryBB();
    ASSERT_NE(sub_bb, nullptr);
    auto sub_itr = sub_bb->begin();
    ExpectInstruction(Next(sub_itr, sub_bb), ir::Opcode::Table::H, {0});
    ExpectInstruction(Next(sub_itr, sub_bb), ir::Opcode::Table::X, {0});
    EXPECT_EQ(ir::Opcode::Table::Return, Next(sub_itr, sub_bb)->GetOpcode().GetCode());
    EXPECT_EQ(sub_itr, sub_bb->end());
}

// Every ControlledWrapper scenario: N=1 direct dispatch, exact-gate-via-And synthesis, rotation
// and GlobalPhase controls, multi-bit and negative-control AND-ladders, nested Controlled, and a
// decomposable sub-circuit.
TEST(QualtranFrontend, ControlledVariants) {
    QualtranFixture fx("controlled_variants");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(25u, func->GetNumQubits());

    constexpr double kEps = 1e-8;

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    for (auto i = 0u; i < 9; ++i) {
        EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // 9 anc_clean Clean hints, one per AND-ladder use.
    }

    // Controlled(XGate()) -> CX.
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {1, 0});
    // Controlled(Hadamard()) -> CHadamard preset call.
    EXPECT_EQ("CHadamard", std::string(ExpectCallOperands(Next(itr, bb), {0, 1})->GetName()));

    // Controlled(TGate()) -> And(compute)-T-And(uncompute).
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {1, 0, 16})->GetName())
    );
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::T, {16});
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {1, 0, 16})->GetName())
    );

    // Controlled(TGate(is_adjoint=True)) -> And(compute)-TDag-And(uncompute).
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {1, 0, 17})->GetName())
    );
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::TDag, {17});
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {1, 0, 17})->GetName())
    );

    // Controlled(Adjoint(TGate())) -> throwaway-Circuit(And(compute)-TDag-And(uncompute))
    // + ReplaceWithAdjoint, dispatched via a __adjoint____controlled__ Call.
    {
        const ir::Function* adj_func = ExpectCallOperands(Next(itr, bb), {0, 1, 18});
        EXPECT_EQ(3u, adj_func->GetNumQubits());
        EXPECT_EQ(4u, adj_func->GetInstructionCount());  // And(compute)+TDag+And(uncompute)+Return
        const ir::BasicBlock* adj_bb = adj_func->GetEntryBB();
        auto adj_itr = adj_bb->begin();
        EXPECT_EQ(
                "And_cv11__compute",
                std::string(ExpectCallOperands(Next(adj_itr, adj_bb), {1, 0, 2})->GetName())
        );
        ExpectInstruction(Next(adj_itr, adj_bb), ir::Opcode::Table::TDag, {2});
        EXPECT_EQ(
                "And_cv11__uncompute",
                std::string(ExpectCallOperands(Next(adj_itr, adj_bb), {1, 0, 2})->GetName())
        );
    }

    // Controlled(XPowGate(exponent=0.5)) -> EmitCXPowGate.
    constexpr auto kQuarterTurn = std::numbers::pi / 4;
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::H, {1});
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 1, kQuarterTurn, kEps / 2);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {1, 0});
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 1, -kQuarterTurn, kEps / 2);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {1, 0});
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::H, {1});
    ExpectGlobalPhase(Next(itr, bb), 0.125, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 0, kQuarterTurn, kEps);

    // Controlled(Rz(angle=pi/4)) -> RZ-CX-RZ-CX.
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 1u, kQuarterTurn / 2.0, kEps / 2.0);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {1, 0});
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 1u, -kQuarterTurn / 2.0, kEps / 2.0);
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {1, 0});

    // Controlled(GlobalPhase(exponent=0.3)) -> GlobalPhase + RZ on ctrl itself.
    ExpectGlobalPhase(Next(itr, bb), 0.15, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 0u, std::numbers::pi * 0.3, kEps);

    // Controlled(XGate(), cvs=0): N=1 negative control, X-wraps ctrl.
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {0});
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {1, 0});
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {0});

    // Controlled(MyGate()): a decomposable sub-circuit dispatched via a __controlled__ Call.
    {
        const ir::Function* sub_func = ExpectCallOperands(Next(itr, bb), {0, 1});
        EXPECT_EQ(2u, sub_func->GetNumQubits());
        EXPECT_EQ(3u, sub_func->GetInstructionCount());  // CX + Call(CHadamard) + Return
        const ir::BasicBlock* sub_bb = sub_func->GetEntryBB();
        auto si = sub_bb->begin();
        ExpectInstruction(Next(si, sub_bb), ir::Opcode::Table::CX, {1, 0});
        EXPECT_EQ(
                "CHadamard", std::string(ExpectCallOperands(Next(si, sub_bb), {0, 1})->GetName())
        );
    }

    // Controlled(CNOT()) -> CCX.
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CCX, {4, 2, 3});

    // Controlled(XGate(), cvs=[1,0,1]): N=3 AND-ladder.
    EXPECT_EQ(
            "And_cv10__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {5, 6, 19})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {19, 7, 20})->GetName())
    );
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {8, 20});
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {19, 7, 20})->GetName())
    );
    EXPECT_EQ(
            "And_cv10__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {5, 6, 19})->GetName())
    );

    // Controlled(Toffoli()): AND-ladder extended by Toffoli's own 2 ctrl qubits.
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {9, 10, 21})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {21, 11, 22})->GetName())
    );
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::CX, {12, 22});
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {21, 11, 22})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {9, 10, 21})->GetName())
    );

    // Controlled(Controlled(TGate())): nested, equivalent to one 2-bit AND control.
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {13, 14, 23})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {15, 23, 24})->GetName())
    );
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::T, {24});
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {15, 23, 24})->GetName())
    );
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {13, 14, 23})->GetName())
    );

    for (auto i = 0u; i < 9; ++i) {
        EXPECT_TRUE(Next(itr, bb)->IsOptHint());  // 9 anc_clean Clean hints, end of scope.
    }
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// EmitBloqCounts always materializes bloq_counts entries right before Return, regardless of their
// source-order interleaving with regular decomposition instructions. ArbitraryCliffordSource is a
// custom Bloq reporting ArbitraryClifford via bloq_counts without IntState, so this doesn't depend
// on IntState's own decomposition; its LOG_WARN "not already emitted via decomposition" branch
// fires but isn't asserted. bloq_counts is a protobuf map, so GlobalPhase order isn't guaranteed
// -- checked as a multiset.
TEST(QualtranFrontend, BloqCountsVariants) {
    QualtranFixture fx("bloq_counts_variants");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(1u, func->GetNumQubits());
    EXPECT_EQ(7u, func->GetInstructionCount());  // X, X, Call(ArbitraryCliffordSource), 3 x
                                                  // GlobalPhase, Return.

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    // Two X gates from the decomposition, materialized in source order (unlike GlobalPhase).
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {0});
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::X, {0});

    // ArbitraryCliffordSource() itself converts to a Call into a Circuit containing a single X.
    {
        const ir::Function* sub_func = ExpectCallOperands(Next(itr, bb), {0});
        EXPECT_EQ(2u, sub_func->GetInstructionCount());  // X + Return
        ExpectInstruction(sub_func->GetEntryBB()->begin().GetPointer(), ir::Opcode::Table::X, {0});
    }

    // All 3 bloq_counts GlobalPhase entries, materialized last regardless of their source-order
    // interleaving with the X gates and the ArbitraryCliffordSource() call above.
    auto phases = std::vector<double>{};
    for (auto i = 0u; i < 3; ++i) {
        const ir::Instruction* inst = Next(itr, bb);
        ASSERT_EQ(ir::Opcode::Table::GlobalPhase, inst->GetOpcode().GetCode());
        const auto* gp = Cast<ir::GlobalPhaseInst>(inst);
        EXPECT_NEAR(1e-8, gp->GetTheta().precision, kTol);
        phases.push_back(gp->GetTheta().value);
    }
    std::ranges::sort(phases);
    EXPECT_NEAR(0.25, phases[0], kTol);
    EXPECT_NEAR(0.5, phases[1], kTol);
    EXPECT_NEAR(0.5, phases[2], kTol);

    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

// LeafRoot fixtures: root itself is atomic (decomposition_size() == 0), one per bloq kind that
// can plausibly appear standalone as a root. Bookkeeping bloqs are not expected to appear
// standalone as a root and are already covered by regression tests elsewhere.

// A directly-mapped gate as root (no ancilla, no synthesis).
TEST(QualtranFrontend, LeafRootHadamard) {
    QualtranFixture fx("leaf_root_hadamard");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(1u, func->GetNumQubits());
    EXPECT_EQ(2u, func->GetInstructionCount());

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();
    const ir::Instruction* inst = Next(itr, bb);
    ASSERT_TRUE(inst->IsUnary());
    EXPECT_EQ(ir::Opcode::Table::H, inst->GetOpcode().GetCode());
    EXPECT_EQ(0u, Cast<ir::UnaryInst>(inst)->GetQubit().id);
}

// A preset CircuitGenerator gate as root (dispatches via a Call, not an inline sequence).
TEST(QualtranFrontend, LeafRootPreset) {
    QualtranFixture fx("leaf_root_preset");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(2u, func->GetNumQubits());
    EXPECT_EQ(2u, func->GetInstructionCount());  // Call(CHadamard) + Return

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();
    const ir::Function* ch_func = ExpectCallOperands(Next(itr, bb), {0, 1});
    EXPECT_EQ("CHadamard", std::string(ch_func->GetName()));
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// CZPowGate as root: a Gate terminal needing its own scratch ancilla.
TEST(QualtranFrontend, LeafRootCzpow) {
    QualtranFixture fx("leaf_root_czpow");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(3u, func->GetNumQubits());  // q[2] + anc_clean.
    EXPECT_EQ(7u, func->GetInstructionCount());

    constexpr double kExp = 0.5;
    constexpr double kEps = 1e-8;

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 2})->GetName())
    );
    ExpectGlobalPhase(Next(itr, bb), kExp / 2.0, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 2u, std::numbers::pi * kExp, kEps);
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 2})->GetName())
    );
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// And() as root: a NewQubitProducer Gate terminal, its own ancilla produced fresh rather than
// forwarded from an existing pool (unlike LeafRootCzpow's).
TEST(QualtranFrontend, LeafRootAndCompute) {
    QualtranFixture fx("leaf_root_and_compute");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(3u, func->GetNumQubits());  // ctrl[2] + target.
    EXPECT_EQ(2u, func->GetInstructionCount());  // Call(And_cv11__compute) + Return

    const auto& argument = circuit->GetArgument();
    ASSERT_EQ(2u, argument.GetNumArgs());
    EXPECT_EQ("ctrl", argument.GetArgName(0));
    EXPECT_EQ("target", argument.GetArgName(1));

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 2})->GetName())
    );
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// An AdjointWrapper as root, unwrapping to a Gate terminal (CZPowGate, exponent negated).
TEST(QualtranFrontend, LeafRootAdjoint) {
    QualtranFixture fx("leaf_root_adjoint");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(3u, func->GetNumQubits());
    EXPECT_EQ(7u, func->GetInstructionCount());

    constexpr double kExp = 0.5;
    constexpr double kEps = 1e-8;

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 2})->GetName())
    );
    ExpectGlobalPhase(Next(itr, bb), -kExp / 2.0, kEps);
    ExpectRotation(Next(itr, bb), ir::Opcode::Table::RZ, 2u, -std::numbers::pi * kExp, kEps);
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {0, 1, 2})->GetName())
    );
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
}

// A ControlledWrapper as root; TGate needs ancilla, exercising that branch.
TEST(QualtranFrontend, LeafRootControlled) {
    QualtranFixture fx("leaf_root_controlled");
    auto* circuit = fx.Build();

    ASSERT_NE(circuit, nullptr);
    const ir::Function* func = circuit->GetIR();
    ASSERT_NE(func, nullptr);

    EXPECT_EQ(3u, func->GetNumQubits());

    const auto& argument = circuit->GetArgument();
    ASSERT_EQ(3u, argument.GetNumArgs());
    EXPECT_EQ("ctrl", argument.GetArgName(0));
    EXPECT_EQ("q", argument.GetArgName(1));
    EXPECT_EQ("anc_clean", argument.GetArgName(2));

    const ir::BasicBlock* bb = func->GetEntryBB();
    ASSERT_NE(bb, nullptr);
    auto itr = bb->begin();

    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(
            "And_cv11__compute",
            std::string(ExpectCallOperands(Next(itr, bb), {1, 0, 2})->GetName())
    );
    ExpectInstruction(Next(itr, bb), ir::Opcode::Table::T, {2});
    EXPECT_EQ(
            "And_cv11__uncompute",
            std::string(ExpectCallOperands(Next(itr, bb), {1, 0, 2})->GetName())
    );
    EXPECT_TRUE(Next(itr, bb)->IsOptHint());
    EXPECT_EQ(ir::Opcode::Table::Return, Next(itr, bb)->GetOpcode().GetCode());
    EXPECT_EQ(itr, bb->end());
}

TEST(QualtranFrontend, MalformedJson) {
    QualtranFixture fx("malformed");
    EXPECT_THROW(fx.BuildFromJson("not valid json {{"), QRETError);
}

TEST(QualtranFrontend, UnsupportedBloq) {
    QualtranFixture fx("unsupported_bloq");
    EXPECT_THROW(fx.Build(), QRETError);
}

TEST(QualtranFrontend, ControlledUnsupportedInt) {
    QualtranFixture fx("controlled_unsupported_int");
    EXPECT_THROW(fx.Build(), QRETError);
}
