function(set_version VERSION)
  # Get Major and Minor from Version.txt
  file(STRINGS "Version.txt" VERSION_STR)
  foreach(STR ${VERSION_STR})
    if(${STR} MATCHES "(.*)")
      set(${VERSION}
          "${CMAKE_MATCH_1}"
          PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

function(add_subdirectory_with_runtime_output directory runtime_output)
  if(MSVC OR "${runtime_output}" STREQUAL "")
    add_subdirectory(${directory})
  else()
    if(DEFINED CMAKE_RUNTIME_OUTPUT_DIRECTORY)
      set(had_runtime_output_directory TRUE)
      set(previous_runtime_output_directory "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    else()
      set(had_runtime_output_directory FALSE)
    endif()
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${runtime_output}")
    add_subdirectory(${directory})
    if(had_runtime_output_directory)
      set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${previous_runtime_output_directory}")
    else()
      unset(CMAKE_RUNTIME_OUTPUT_DIRECTORY)
    endif()
  endif()
endfunction()
