/**
 * @file qret/math/clifford.h
 * @brief Stabilizer group and stabilizer tableau.
 */

#ifndef QRET_MATH_CLIFFORD_H
#define QRET_MATH_CLIFFORD_H

#include <boost/dynamic_bitset.hpp>
#include <boost/dynamic_bitset/dynamic_bitset.hpp>

#include <cstddef>
#include <cstdint>
#include <vector>

#include "qret/math/pauli.h"
#include "qret/qret_export.h"

namespace qret::math {
/**
 * @brief Stabilizer group.
 */
class QRET_EXPORT StabilizerGroup {
public:
    /**
     * @brief Construct a new stabilizer group which stabilizes |00...0>.
     *
     * @param num_qubits the number of qubits
     */
    explicit StabilizerGroup(std::size_t num_qubits);

    /**
     * @brief Construct a new stabilizer group generated by pauli strings.
     *
     * If \p generators do not satisfy the condition of stabilizer group, throws exception.
     *
     * @param num_qubits
     * @param generators stabilizer generators
     */
    explicit StabilizerGroup(std::size_t num_qubits, const std::vector<PauliString>& generators);

    PauliString& operator[](std::size_t i) {
        return generators_[i];
    }
    const PauliString& operator[](std::size_t i) const {
        return generators_[i];
    }

    [[nodiscard]] std::size_t GetNumQubits() const {
        return num_qubits_;
    }
    [[nodiscard]] std::size_t GetNumStabilizerGenerators() const {
        return generators_.size();
    }

    [[nodiscard]] auto begin() {
        return generators_.begin();
    }
    [[nodiscard]] auto begin() const {
        return generators_.begin();
    }
    [[nodiscard]] auto end() {
        return generators_.end();
    }
    [[nodiscard]] auto end() const {
        return generators_.end();
    }

    [[nodiscard]] auto cbegin() {
        return generators_.cbegin();
    }
    [[nodiscard]] auto cbegin() const {
        return generators_.cbegin();
    }
    [[nodiscard]] auto cend() {
        return generators_.cend();
    }
    [[nodiscard]] auto cend() const {
        return generators_.cend();
    }

    /**
     * @brief Validate stabilizer group.
     *
     * Conditions of stabilizer generators:
     *
     * * All stabilizer generators have the same qubit size.
     * * Stabilizer generator's phase is -1 or 1.
     * * All stabilizer generators are commutative.
     * * Stabilizer generators do not generate -I.
     * * Stabilizer generators are independent.
     */
    void Validate() const;

    /**
     * @brief Normalize stabilizer group.
     */
    void NormalizeInPlace();
    StabilizerGroup Normalized() const;

    /**
     * @brief Check if \p pauli is commute with all stabilizer generators.
     *
     * @param pauli
     * @return true if they commute, false otherwise.
     */
    [[nodiscard]] bool IsCommuteWithAll(const PauliString& pauli) const {
        for (const auto& generator : generators_) {
            if (!generator.IsCommuteWith(pauli)) {
                return false;
            }
        }
        return true;
    }

    /**
     * @brief if s * pauli is in this group for some s in {1,-1,i,-i}, return the sign s.
     *
     * @param pauli
     * @return Pair of (pauli is stabilizer or not, sign)
     */
    std::tuple<bool, std::uint8_t> CalculateSign(PauliString pauli) const;

private:
    std::vector<PauliString> NormalizedGenerators() const;

    std::size_t num_qubits_;
    std::vector<PauliString> generators_;
};

/**
 * @brief Stabilizer Tableau.
 */
class QRET_EXPORT StabilizerTableau {
public:
    using BitSet = PauliString::BitSet;

    static StabilizerTableau FromPauliString(const PauliString& pauli);

    static StabilizerTableau X(std::size_t num_qubits, std::uint64_t q);
    static StabilizerTableau Y(std::size_t num_qubits, std::uint64_t q);
    static StabilizerTableau Z(std::size_t num_qubits, std::uint64_t q);
    static StabilizerTableau H(std::size_t num_qubits, std::uint64_t q);
    static StabilizerTableau S(std::size_t num_qubits, std::uint64_t q);
    static StabilizerTableau SDag(std::size_t num_qubits, std::uint64_t q);
    static StabilizerTableau CX(std::size_t num_qubits, std::uint64_t t, std::uint64_t c);
    static StabilizerTableau CY(std::size_t num_qubits, std::uint64_t t, std::uint64_t c);
    static StabilizerTableau CZ(std::size_t num_qubits, std::uint64_t t, std::uint64_t c);

    /**
     * @brief Apply clifford gate to pauli string.
     * @details pauli_string.num_qubits and num_qubits must be same.
     *
     * @param pauli Pauli string to apply clifford gate.
     */
    void Apply(PauliString& pauli) const;

    void Apply(StabilizerGroup& stabilizer_group) const {
        for (auto&& generator : stabilizer_group) {
            Apply(generator);
        }
    }

    /**
     * @brief Get the number of qubits.
     */
    std::size_t GetNumQubits() const {
        return num_qubits_;
    }

    /**
     * @brief Get the number of targets.
     */
    std::size_t GetNumTargets() const {
        return target_idx_.size();
    }

    const std::vector<PauliString>& XS() const {
        return xs_;
    }
    const std::vector<PauliString>& ZS() const {
        return zs_;
    }

private:
    StabilizerTableau(
            std::size_t num_qubits,
            const std::vector<std::size_t>& target_idx,
            const std::vector<PauliString>& xs,
            const std::vector<PauliString>& zs
    );

    std::size_t num_qubits_;
    std::vector<std::size_t> target_idx_;

    std::vector<PauliString> xs_;  //!< size = number of targets, X_i -> XS[i]
    std::vector<PauliString> zs_;  //!< size = number of targets, Z_i -> ZS[i]
};

QRET_EXPORT inline bool operator==(const StabilizerTableau& lhs, const StabilizerTableau& rhs) {
    if (lhs.GetNumQubits() != rhs.GetNumQubits()) {
        return false;
    }
    if (lhs.GetNumTargets() != rhs.GetNumTargets()) {
        return false;
    }
    for (auto i = std::size_t{0}; i < lhs.GetNumTargets(); ++i) {
        if (lhs.XS()[i] != rhs.XS()[i]) {
            return false;
        }
        if (lhs.ZS()[i] != rhs.ZS()[i]) {
            return false;
        }
    }
    return true;
}
}  // namespace qret::math

#endif  // QRET_MATH_CLIFFORD_H
